FROM registry.access.redhat.com/ubi9/ubi
LABEL maintainer="Shion Tanaka / Twitter(@tnk4on)"
RUN dnf update -y
RUN dnf install ruby ruby-devel g++ git -y
RUN dnf clean all 
RUN gem install jekyll
WORKDIR /workspaces
#RUN bundle install
#RUN echo $PWD